### ISSUE TITLE
iOS 10.3.1 - Keeps asking to update the Linkedin app

### ISSUE THREAD

**Issue by asalgueiro** [zyra/cordova-plugin-linkedin#9]
When try to login, the plugin ask to update the Linkedin app but the version installed is the lastest from the App Store. With the flag promptToInstall in false, the plugins throws the error: ERROR = Error Domain=LISDKAuthError Code=6

My code is

        cordova.plugins.LinkedIn.hasActiveSession(function(exists) {
          if (exists) {
              // login ok

          } else {
            cordova.plugins.LinkedIn.login(['r_basicprofile', 'r_emailaddress'], true, function() {
              // login ok

            }, function (error){
              // error
              alert(error);
            });
          } /* if else */
        });

Thanks

**Comment by ihadeed** [comment]
Thanks for reporting this. I will look into it.

**Comment by naveedahmed1** [comment]
@ihadeed  Is it fixed now?

**Comment by ihadeed** [comment]
@naveedahmed1 I haven't managed to reproduce it yet. I don't own an iOS 10.x device. It works well on iOS 9.x though.

My guess is that the LinkedIn SDK or App has an issue. They haven't published any new updates to their SDK but they did publish a few app updates on iOS. I would appreciate it if you can try this again and let me know if it's still an issue, as I have no way at the moment to try and reproduce it.

**Comment by asalgueiro** [comment]
@ihadeed thanks for your time, but the problem still persists. 
When i call the login() method the device halts for a couple of seconds and then appear the Update app dialog.  The linkedin app is installed in their last version.

**Comment by ihadeed** [comment]
@asalgueiro not sure what to do here.

- I tested this on my older iOS device with no problems, I don't have iOS 10.x to test this on
- I searched the web for a similar error and I couldn't find anything
- [My implementation](https://github.com/zyra/cordova-plugin-linkedin/blob/master/src/ios/LinkedIn.m#L36-L46) matches [their docs ](https://developer.linkedin.com/docs/ios-sdk-auth) exactly

I will keep this issue open in case anyone wants to help reproduce it or provide a fix. But as of now I can't confirm that the bug exist or try and do anything about it.

LinkedIn's SDK is not open source, their docs is very poor, and they provide no way to ask for support...

**Comment by PaolinoD** [comment]
Hi @asalgueiro,

at the moment I do not have the opportunity to do new tests, but I remember having used devices with iOS 10.x to do the tests of my application and I had no problems.

Or rather, I experieced a problem similar to your: due to a hook that I'm using, a setting, that should be added in the prepare phase after adding the plugin, was overwritten.

Following are the keys of the setting i was speaking about and that should be found in the Info.plist of your application (in addition to other keys if needed):
`        <config-file target="*-Info.plist" parent="LSApplicationQueriesSchemes">`
`            <array>`
`                <string>linkedin</string>`
`                <string>linkedin-sdk2</string>`
`                <string>linkedin-sdk</string>`
`            </array>`
`        </config-file>`

If these keys are not there, devices with iOS 9.x and 10.x are not able to open applications that use these schemes, thus potentially resulting in the error
`ERROR = Error`
`Domain=LISDKAuthError`
`Code=6`
that according to [LISDKErrorCode.h](https://github.com/zyra/cordova-plugin-linkedin/blob/master/src/ios/linkedin-sdk.framework/Headers/LISDKErrorCode.h) seems to be thrown when LinkedIn app is not installed or needs an update.

If you have access on the Info.plist, would you take a look at the file content to verify if the keys i wrote are there?

For more details on the key, here is the [link](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/TP40009250-SW14) on the Apple official doc.

Let me know if that solved your issue, or at least helped youin such way ;)

--p

**Comment by Sampath-Lokuge** [comment]
@ihadeed Hope this will help you to get the support from Linkedin:https://developer.linkedin.com/support
